services:
  - type: web
    name: smart-event-planner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: sqlite:///./smart_event_planner.db
      - key: OPENWEATHERMAP_API_KEY
        sync: false  # This means you'll need to set this value manually in the Render dashboard 